#!/usr/bin/env node
/**
 * npm run setup:local [--force]
 *
 * 1. Writes supabase/functions/.env (the CLI's default --env-file) with fresh
 *    random FIELD_ENCRYPTION_KEY, DISPENSER_SHARED_SECRET, OTP_PEPPER,
 *    SEED_SECRET plus OTP_PROVIDER=mock, POLICY_VERSION, ALLOWED_ORIGINS and
 *    PUBLIC_SUPABASE_URL. Existing secrets are KEPT unless --force.
 * 2. Reads the local API URL + anon key from `npx supabase status` and writes
 *    them to .env.local for Vite.
 * Never prints secret values.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { envWithDocker } from './docker-path.mjs';

const force = process.argv.includes('--force');
const root = path.resolve(new URL('..', import.meta.url).pathname);
const FN_ENV = path.join(root, 'supabase', 'functions', '.env');
const LOCAL_ENV = path.join(root, '.env.local');
const POLICY_VERSION = '2025-01'; // keep in sync with VITE_POLICY_VERSION

function parseEnv(file) {
  const map = new Map();
  if (!fs.existsSync(file)) return map;
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

function writeEnv(file, header, entries) {
  const body = entries.map(([k, v]) => `${k}=${v}`).join('\n');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${header}\n${body}\n`);
}

function supabaseStatus() {
  // `supabase status` exits non-zero when OPTIONAL services (imgproxy, pooler)
  // are stopped, even though the stack is usable — so judge by whether we can
  // parse the JSON payload, not by the exit code.
  const r = spawnSync(path.join(root, 'node_modules', '.bin', 'supabase'), ['status', '-o', 'json'], {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    env: envWithDocker(),
  });
  const out = `${r.stdout ?? ''}\n${r.stderr ?? ''}`;
  const start = out.indexOf('{');
  const end = out.lastIndexOf('}');
  if (start >= 0 && end > start) {
    try {
      return JSON.parse(out.slice(start, end + 1));
    } catch {
      /* fall through to the error below */
    }
  }
  console.error('\n✖ Could not read the local Supabase status. Is the stack running?\n    npm run sb:start\n');
  if (out.trim()) console.error(out.trim().split('\n').slice(0, 6).join('\n'));
  process.exit(1);
}

// ---------------------------------------------------------------------------
const status = supabaseStatus();
const apiUrl = status.API_URL || 'http://127.0.0.1:54321';
const anonKey = status.ANON_KEY;
if (!anonKey) {
  console.error('✖ `supabase status` did not return ANON_KEY.');
  process.exit(1);
}

// 1) supabase/functions/.env --------------------------------------------------
const existing = parseEnv(FN_ENV);
const secrets = {
  FIELD_ENCRYPTION_KEY: () => randomBytes(32).toString('base64'),
  DISPENSER_SHARED_SECRET: () => randomBytes(32).toString('hex'),
  OTP_PEPPER: () => randomBytes(32).toString('base64'),
  SEED_SECRET: () => randomBytes(32).toString('hex'),
};
const defaults = {
  OTP_PROVIDER: 'mock',
  DEMO_MODE: 'false', // staging demo bypass — see supabase/.env.example
  POLICY_VERSION,
  ALLOWED_ORIGINS: 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173',
  PUBLIC_SUPABASE_URL: apiUrl,
};

const fnEntries = [];
const report = [];
for (const [key, gen] of Object.entries(secrets)) {
  if (existing.has(key) && !force) {
    fnEntries.push([key, existing.get(key)]);
    report.push(`  ${key.padEnd(24)} kept existing`);
  } else {
    fnEntries.push([key, gen()]);
    report.push(`  ${key.padEnd(24)} ${existing.has(key) ? 'REGENERATED (--force)' : 'generated'}`);
  }
}
for (const [key, val] of Object.entries(defaults)) {
  const v = existing.has(key) && !force ? existing.get(key) : val;
  fnEntries.push([key, v]);
  report.push(`  ${key.padEnd(24)} ${existing.has(key) && !force ? 'kept existing' : `= ${v}`}`);
}
// Preserve any extra keys the user added (e.g. TWILIO_*).
for (const [k, v] of existing) if (!fnEntries.some(([ek]) => ek === k)) fnEntries.push([k, v]);

writeEnv(
  FN_ENV,
  '# Local Edge Function secrets — generated by `npm run setup:local`. Gitignored. Never commit.',
  fnEntries,
);

// 2) .env.local ---------------------------------------------------------------
const local = parseEnv(LOCAL_ENV);
local.set('VITE_SUPABASE_URL', apiUrl);
local.set('VITE_SUPABASE_ANON_KEY', anonKey);
if (!local.has('VITE_POLICY_VERSION')) local.set('VITE_POLICY_VERSION', POLICY_VERSION);
writeEnv(LOCAL_ENV, '# Local Vite env — generated by `npm run setup:local`. Gitignored.', [...local]);

console.log(`\n✔ supabase/functions/.env\n${report.join('\n')}`);
console.log(`\n✔ .env.local\n  VITE_SUPABASE_URL        = ${apiUrl}\n  VITE_SUPABASE_ANON_KEY   = (local anon key)\n`);
console.log('Next:  npm run sb:reset   then   npm run sb:functions   (and   npm run dev   in another terminal)\n');
